create table alt.dim_menu_category (
  menu_public_code varchar,
  menu_name varchar,
  category_name varchar,
  category_id varchar,
  update_time timestamp
)

insert into alt.dim_menu_category values
('MNU0000071','アクション','action','CAT0001',now()),
('MNU0000065','ラブロマンス','romance','CAT0002',now()),
('MNU0000078','サスペンス・ミステリー','mystery','CAT0003',now()),
('MNU0000079','コメディ','comedy','CAT0004',now()),
('MNU0000064','ラブコメディ','romance','CAT0002',now()),
('MNU0000039','コメディ','comedy','CAT0004',now()),
('MNU0000038','サスペンス・ミステリー','mystery','CAT0003',now()),
('MNU0000009','ファンタジー','fantasy','CAT0005',now()),
('MNU0000030','ドキュメンタリー','documentary','CAT0006',now()),
('MNU0000005','ラブコメディ','romance','CAT0002',now()),
('MNU0000037','アクション','action','CAT0001',now()),
('MNU0000003','歴史・時代劇','historical','CAT0007',now()),
('MNU0000023','コメディ','comedy','CAT0004',now()),
('MNU0000014','ラブストーリー','romance','CAT0002',now()),
('MNU0000021','SF','SF','CAT0008',now()),
('MNU0000052','アクション','action','CAT0001',now()),
('MNU0000011','アクション・バトル','action','CAT0001',now()),
('MNU0000029','史劇','historical','CAT0007',now()),
('MNU0000028','戦争','war','CAT0009',now()),
('MNU0000007','SF','SF','CAT0008',now()),
('MNU0000045','ドキュメンタリー','documentary','CAT0006',now()),
('MNU0000040','ラブストーリー・ラブコメディ','romance','CAT0002',now()),
('MNU0000081','ホラー・パニック','horror','CAT0010',now()),
('MNU0000080','ラブストーリー・ラブコメディ','romance','CAT0002',now()),
('MNU0000041','ホラー・パニック','horror','CAT0010',now()),
('MNU0000103','音楽','music','CAT0011',now()),
('MNU0000048','ロマンスシネマ','romance','CAT0002',now()),
('MNU0000104','ドキュメンタリー','documentary','CAT0006',now()),
('MNU0000057','ホラー','horror','CAT0010',now()),
('MNU0000008','サスペンス・ミステリー','mystery','CAT0003',now()),
('MNU0000010','ミリタリー','war','CAT0009',now()),
('MNU0000042','歴史・時代劇','historical','CAT0007',now()),
('MNU0000027','ミュージカル・音楽','music','CAT0011',now()),
('MNU0000056','ラブストーリー・ラブコメディ','romance','CAT0002',now()),
('MNU0000097','うたっておどろう♪','music','CAT0011',now()),
('MNU0000086','歴史・時代劇','historical','CAT0007',now()),
('MNU0000024','ラブストーリー・ラブコメディ','romance','CAT0002',now()),
('MNU0000055','コメディ','comedy','CAT0004',now()),
('MNU0000025','ホラー・パニック','horror','CAT0010',now()),
('MNU0000026','ファンタジー・アドベンチャー','fantasy','CAT0005',now()),
('MNU0000084','刑事・探偵','detective','CAT0012',now()),
('MNU0000068','コメディ','comedy','CAT0004',now()),
('MNU0000070','サスペンス・ミステリー','mystery','CAT0003',now()),
('MNU0000053','SF','SF','CAT0008',now()),
('MNU0000069','歴史・時代劇','historical','CAT0007',now()),
('MNU0000020','アクション','action','CAT0001',now()),
('MNU0000015','ファミリー・キッズ','family','CAT0013',now()),
('MNU0000022','サスペンス・ミステリー','mystery','CAT0003',now()),
('MNU0000054','サスペンス・ミステリー','mystery','CAT0003',now()),
('MNU0000059','刑事・探偵','detective','CAT0012',now())


create table alt.dim_sakuhin_category
(
  sakuhin_category_id varchar,
  sakuhin_public_code varchar,
  sakuhin_name varchar,
  main_genre_code varchar,
  category_id varchar,
  category_name varchar
)


/*insert into alt.dim_sakuhin_category (
select
  distinct
  sakuhin_public_code || category_id as sakuhin_category_id,
  sakuhin_public_code,
  dsm.display_name,
  main_genre_code,
  category_name,
  category_id
from dim_sakuhin_menu dsm
inner join dim_sakuhin using(sakuhin_public_code)
inner join alt.dim_menu_category using(menu_public_code)
)*/


create table alt.dim_alt_category (
  alt_public_code varchar,
  main_genre_code varchar,
  category_name varchar
)


insert into alt.dim_alt_category values
('ALT000041','ADRAMA','action'),
('ALT000042','ADRAMA','historical'),
('ALT000043','ADRAMA','mystery'),
('ALT000044','ADRAMA','romance'),
('ALT000045','ANIME','action'),
('ALT000046','ANIME','family'),
('ALT000047','ANIME','fantasy'),
('ALT000048','ANIME','historical'),
('ALT000049','ANIME','mystery'),
('ALT000050','ANIME','romance'),
('ALT000051','ANIME','SF'),
('ALT000052','ANIME','war'),
('ALT000053','DRAMA','comedy'),
('ALT000054','DRAMA','detective'),
('ALT000055','DRAMA','historical'),
('ALT000056','DRAMA','mystery'),
('ALT000057','DRAMA','romance'),
('ALT000058','FDRAMA','action'),
('ALT000059','FDRAMA','comedy'),
('ALT000060','FDRAMA','detective'),
('ALT000061','FDRAMA','horror'),
('ALT000062','FDRAMA','mystery'),
('ALT000063','FDRAMA','romance'),
('ALT000064','FDRAMA','SF'),
('ALT000065','HOUGA','action'),
('ALT000066','HOUGA','comedy'),
('ALT000067','HOUGA','documentary'),
('ALT000068','HOUGA','historical'),
('ALT000069','HOUGA','horror'),
('ALT000070','HOUGA','mystery'),
('ALT000071','HOUGA','romance'),
('ALT000072','KIDS','action'),
('ALT000073','KIDS','family'),
('ALT000074','KIDS','fantasy'),
('ALT000075','KIDS','music'),
('ALT000076','VARIETY','documentary'),
('ALT000077','YOUGA','action'),
('ALT000078','YOUGA','comedy'),
('ALT000079','YOUGA','documentary'),
('ALT000080','YOUGA','fantasy'),
('ALT000081','YOUGA','historical'),
('ALT000082','YOUGA','horror'),
('ALT000083','YOUGA','music'),
('ALT000084','YOUGA','mystery'),
('ALT000085','YOUGA','romance'),
('ALT000086','YOUGA','SF'),
('ALT000087','YOUGA','war'),
('ALT000088','FDRAMA',Null),
('ALT000089','MUSIC',Null),
('ALT000090','VARIETY',Null),
('ALT000091','ANIME',Null),
('ALT000092','YOUGA',Null),
('ALT000093','DRAMA',Null),
('ALT000094','ADRAMA',Null),
('ALT000095','DOCUMENT',Null),
('ALT000096','HOUGA',Null),
('ALT000097','KIDS',Null)


create table alt.dim_alt
(
  alt_public_code varchar,
  alt_name varchar,
  alt_description varchar,
  alt_type varchar,
  alt_sub_type varchar,
  main_genre_code varchar,
  alt_generation_type varchar,
  update_time timestamp 
)


insert into alt.dim_alt values
('ALT000001','新着作品ランキング','ユーネクストで最近配信作品ランキング！','BUSINESS','NEW_ARRIVAL','SOUGOU','PERSONALIZED',now()),
('ALT000002','新着洋画作品ランキング','ユーネクストで最近配信洋画作品ランキング！','BUSINESS','NEW_ARRIVAL','YOUGA','PERSONALIZED',now()),
('ALT000003','新着邦画作品ランキング','ユーネクストで最近配信邦画作品ランキング！','BUSINESS','NEW_ARRIVAL','HOUGA','PERSONALIZED',now()),
('ALT000004','新着漫画作品ランキング','ユーネクストで最近配信漫画作品ランキング！','BUSINESS','NEW_ARRIVAL','ANIME','PERSONALIZED',now()),
('ALT000005','新着海外ドラマ作品ランキング','ユーネクストで最近配信海外ドラマ作品ランキング！','BUSINESS','NEW_ARRIVAL','FDRAMA','PERSONALIZED',now()),
('ALT000006','新着バラエティ作品ランキング','ユーネクストで最近配信バラエティ作品ランキング！','BUSINESS','NEW_ARRIVAL','VARIETY','PERSONALIZED',now()),
('ALT000007','新着音楽作品ランキング','ユーネクストで最近配信音楽作品ランキング！','BUSINESS','NEW_ARRIVAL','MUSIC_IDOL','PERSONALIZED',now()),
('ALT000008','新着スポーツ作品ランキング','ユーネクストで最近配信スポーツ作品ランキング！','BUSINESS','NEW_ARRIVAL','SPORT','PERSONALIZED',now()),
('ALT000009','新着ドラマ作品ランキング','ユーネクストで最近配信ドラマ作品ランキング！','BUSINESS','NEW_ARRIVAL','DRAMA','PERSONALIZED',now()),
('ALT000010','新着アジアドラマ作品ランキング','ユーネクストで最近配信アジアドラマ作品ランキング！','BUSINESS','NEW_ARRIVAL','ADRAMA','PERSONALIZED',now()),
('ALT000011','新着ニュース作品ランキング','ユーネクストで最近配信ニュース作品ランキング！','BUSINESS','NEW_ARRIVAL','NEWS','PERSONALIZED',now()),
('ALT000012','新着ドキュメント作品ランキング','ユーネクストで最近配信ドキュメント作品ランキング！','BUSINESS','NEW_ARRIVAL','DOCUMENT','PERSONALIZED',now()),
('ALT000013','新着キッズ作品ランキング','ユーネクストで最近配信キッズ作品ランキング！','BUSINESS','NEW_ARRIVAL','KIDS','PERSONALIZED',now()),
('ALT000014','週間洋画作品ランキング','ユーネクストで洋画作品週間ランキング！','BUSINESS','WEEKLY_RANKING','YOUGA','KOTEI',now()),
('ALT000015','週間邦画作品ランキング','ユーネクストで邦画作品週間ランキング！','BUSINESS','WEEKLY_RANKING','HOUGA','KOTEI',now()),
('ALT000016','週間漫画作品ランキング','ユーネクストで漫画作品週間ランキング！','BUSINESS','WEEKLY_RANKING','ANIME','KOTEI',now()),
('ALT000017','週間海外ドラマ作品ランキング','ユーネクストで海外ドラマ作品週間ランキング！','BUSINESS','WEEKLY_RANKING','FDRAMA','KOTEI',now()),
('ALT000018','週間バラエティ作品ランキング','ユーネクストでバラエティ作品週間ランキング！','BUSINESS','WEEKLY_RANKING','VARIETY','KOTEI',now()),
('ALT000019','週間音楽作品ランキング','ユーネクストで音楽作品週間ランキング！','BUSINESS','WEEKLY_RANKING','MUSIC_IDOL','KOTEI',now()),
('ALT000020','週間スポーツ作品ランキング','ユーネクストでスポーツ作品週間ランキング！','BUSINESS','WEEKLY_RANKING','SPORT','KOTEI',now()),
('ALT000021','週間ドラマ作品ランキング','ユーネクストでドラマ作品週間ランキング！','BUSINESS','WEEKLY_RANKING','DRAMA','KOTEI',now()),
('ALT000022','週間アジアドラマ作品ランキング','ユーネクストでアジアドラマ作品週間ランキング！','BUSINESS','WEEKLY_RANKING','ADRAMA','KOTEI',now()),
('ALT000023','週間ニュース作品ランキング','ユーネクストでニュース作品週間ランキング！','BUSINESS','WEEKLY_RANKING','NEWS','KOTEI',now()),
('ALT000024','週間ドキュメント作品ランキング','ユーネクストでドキュメント作品週間ランキング！','BUSINESS','WEEKLY_RANKING','DOCUMENT','KOTEI',now()),
('ALT000025','週間キッズ作品ランキング','ユーネクストでキッズ作品週間ランキング！','BUSINESS','WEEKLY_RANKING','KIDS','KOTEI',now()),
('ALT000026','週間作品ランキング','ユーネクストで作品週間ランキング！','BUSINESS','WEEKLY_RANKING','SOUGOU','KOTEI',now()),
('ALT000027','まもなく配信終了','ユーネクストでまもなく配信終了！','BUSINESS','EXPIRE_SOON','SOUGOU','PERSONALIZED',now()),
('ALT000028','人気急上昇作品','ユーネクストで人気急上昇作品！','BUSINESS','TRENDING','SOUGOU','PERSONALIZED',now()),
('ALT000029','人気急上昇洋画作品','ユーネクストで人気急上昇洋画作品！','BUSINESS','TRENDING','YOUGA','PERSONALIZED',now()),
('ALT000030','人気急上昇邦画作品','ユーネクストで人気急上昇邦画作品！','BUSINESS','TRENDING','HOUGA','PERSONALIZED',now()),
('ALT000031','人気急上昇漫画作品','ユーネクストで人気急上昇漫画作品！','BUSINESS','TRENDING','ANIME','PERSONALIZED',now()),
('ALT000032','人気急上昇海外ドラマ作品','ユーネクストで人気急上昇海外ドラマ作品！','BUSINESS','TRENDING','FDRAMA','PERSONALIZED',now()),
('ALT000033','人気急上昇バラエティ作品','ユーネクストで人気急上昇バラエティ作品！','BUSINESS','TRENDING','VARIETY','PERSONALIZED',now()),
('ALT000034','人気急上昇音楽作品','ユーネクストで人気急上昇音楽作品！','BUSINESS','TRENDING','MUSIC_IDOL','PERSONALIZED',now()),
('ALT000035','人気急上昇スポーツ作品','ユーネクストで人気急上昇スポーツ作品！','BUSINESS','TRENDING','SPORT','PERSONALIZED',now()),
('ALT000036','人気急上昇ドラマ作品','ユーネクストで人気急上昇ドラマ作品！','BUSINESS','TRENDING','DRAMA','PERSONALIZED',now()),
('ALT000037','人気急上昇アジアドラマ作品','ユーネクストで人気急上昇アジアドラマ作品！','BUSINESS','TRENDING','ADRAMA','PERSONALIZED',now()),
('ALT000038','人気急上昇ニュース作品','ユーネクストで人気急上昇ニュース作品！','BUSINESS','TRENDING','NEWS','PERSONALIZED',now()),
('ALT000039','人気急上昇ドキュメント作品','ユーネクストで人気急上昇ドキュメント作品！','BUSINESS','TRENDING','DOCUMENT','PERSONALIZED',now()),
('ALT000040','人気急上昇キッズ作品','ユーネクストで人気急上昇キッズ作品！','BUSINESS','TRENDING','KIDS','PERSONALIZED',now()),
('ALT000041','オルトカテ_ADRAMA_action','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ADRAMA','PERSONALIZED',now()),
('ALT000042','オルトカテ_ADRAMA_historical','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ADRAMA','PERSONALIZED',now()),
('ALT000043','オルトカテ_ADRAMA_mystery','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ADRAMA','PERSONALIZED',now()),
('ALT000044','オルトカテ_ADRAMA_romance','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ADRAMA','PERSONALIZED',now()),
('ALT000045','オルトカテ_ANIME_action','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ANIME','PERSONALIZED',now()),
('ALT000046','オルトカテ_ANIME_family','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ANIME','PERSONALIZED',now()),
('ALT000047','オルトカテ_ANIME_fantasy','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ANIME','PERSONALIZED',now()),
('ALT000048','オルトカテ_ANIME_historical','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ANIME','PERSONALIZED',now()),
('ALT000049','オルトカテ_ANIME_mystery','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ANIME','PERSONALIZED',now()),
('ALT000050','オルトカテ_ANIME_romance','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ANIME','PERSONALIZED',now()),
('ALT000051','オルトカテ_ANIME_SF','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ANIME','PERSONALIZED',now()),
('ALT000052','オルトカテ_ANIME_war','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ANIME','PERSONALIZED',now()),
('ALT000053','オルトカテ_DRAMA_comedy','オルトカテ','CONTENT_BASED','ALT_CATEGORY','DRAMA','PERSONALIZED',now()),
('ALT000054','オルトカテ_DRAMA_detective','オルトカテ','CONTENT_BASED','ALT_CATEGORY','DRAMA','PERSONALIZED',now()),
('ALT000055','オルトカテ_DRAMA_historical','オルトカテ','CONTENT_BASED','ALT_CATEGORY','DRAMA','PERSONALIZED',now()),
('ALT000056','オルトカテ_DRAMA_mystery','オルトカテ','CONTENT_BASED','ALT_CATEGORY','DRAMA','PERSONALIZED',now()),
('ALT000057','オルトカテ_DRAMA_romance','オルトカテ','CONTENT_BASED','ALT_CATEGORY','DRAMA','PERSONALIZED',now()),
('ALT000058','オルトカテ_FDRAMA_action','オルトカテ','CONTENT_BASED','ALT_CATEGORY','FDRAMA','PERSONALIZED',now()),
('ALT000059','オルトカテ_FDRAMA_comedy','オルトカテ','CONTENT_BASED','ALT_CATEGORY','FDRAMA','PERSONALIZED',now()),
('ALT000060','オルトカテ_FDRAMA_detective','オルトカテ','CONTENT_BASED','ALT_CATEGORY','FDRAMA','PERSONALIZED',now()),
('ALT000061','オルトカテ_FDRAMA_horror','オルトカテ','CONTENT_BASED','ALT_CATEGORY','FDRAMA','PERSONALIZED',now()),
('ALT000062','オルトカテ_FDRAMA_mystery','オルトカテ','CONTENT_BASED','ALT_CATEGORY','FDRAMA','PERSONALIZED',now()),
('ALT000063','オルトカテ_FDRAMA_romance','オルトカテ','CONTENT_BASED','ALT_CATEGORY','FDRAMA','PERSONALIZED',now()),
('ALT000064','オルトカテ_FDRAMA_SF','オルトカテ','CONTENT_BASED','ALT_CATEGORY','FDRAMA','PERSONALIZED',now()),
('ALT000065','オルトカテ_HOUGA_action','オルトカテ','CONTENT_BASED','ALT_CATEGORY','HOUGA','PERSONALIZED',now()),
('ALT000066','オルトカテ_HOUGA_comedy','オルトカテ','CONTENT_BASED','ALT_CATEGORY','HOUGA','PERSONALIZED',now()),
('ALT000067','オルトカテ_HOUGA_documentary','オルトカテ','CONTENT_BASED','ALT_CATEGORY','HOUGA','PERSONALIZED',now()),
('ALT000068','オルトカテ_HOUGA_historical','オルトカテ','CONTENT_BASED','ALT_CATEGORY','HOUGA','PERSONALIZED',now()),
('ALT000069','オルトカテ_HOUGA_horror','オルトカテ','CONTENT_BASED','ALT_CATEGORY','HOUGA','PERSONALIZED',now()),
('ALT000070','オルトカテ_HOUGA_mystery','オルトカテ','CONTENT_BASED','ALT_CATEGORY','HOUGA','PERSONALIZED',now()),
('ALT000071','オルトカテ_HOUGA_romance','オルトカテ','CONTENT_BASED','ALT_CATEGORY','HOUGA','PERSONALIZED',now()),
('ALT000072','オルトカテ_KIDS_action','オルトカテ','CONTENT_BASED','ALT_CATEGORY','KIDS','PERSONALIZED',now()),
('ALT000073','オルトカテ_KIDS_family','オルトカテ','CONTENT_BASED','ALT_CATEGORY','KIDS','PERSONALIZED',now()),
('ALT000074','オルトカテ_KIDS_fantasy','オルトカテ','CONTENT_BASED','ALT_CATEGORY','KIDS','PERSONALIZED',now()),
('ALT000075','オルトカテ_KIDS_music','オルトカテ','CONTENT_BASED','ALT_CATEGORY','KIDS','PERSONALIZED',now()),
('ALT000076','オルトカテ_VARIETY_documentary','オルトカテ','CONTENT_BASED','ALT_CATEGORY','VARIETY','PERSONALIZED',now()),
('ALT000077','オルトカテ_YOUGA_action','オルトカテ','CONTENT_BASED','ALT_CATEGORY','YOUGA','PERSONALIZED',now()),
('ALT000078','オルトカテ_YOUGA_comedy','オルトカテ','CONTENT_BASED','ALT_CATEGORY','YOUGA','PERSONALIZED',now()),
('ALT000079','オルトカテ_YOUGA_documentary','オルトカテ','CONTENT_BASED','ALT_CATEGORY','YOUGA','PERSONALIZED',now()),
('ALT000080','オルトカテ_YOUGA_fantasy','オルトカテ','CONTENT_BASED','ALT_CATEGORY','YOUGA','PERSONALIZED',now()),
('ALT000081','オルトカテ_YOUGA_historical','オルトカテ','CONTENT_BASED','ALT_CATEGORY','YOUGA','PERSONALIZED',now()),
('ALT000082','オルトカテ_YOUGA_horror','オルトカテ','CONTENT_BASED','ALT_CATEGORY','YOUGA','PERSONALIZED',now()),
('ALT000083','オルトカテ_YOUGA_music','オルトカテ','CONTENT_BASED','ALT_CATEGORY','YOUGA','PERSONALIZED',now()),
('ALT000084','オルトカテ_YOUGA_mystery','オルトカテ','CONTENT_BASED','ALT_CATEGORY','YOUGA','PERSONALIZED',now()),
('ALT000085','オルトカテ_YOUGA_romance','オルトカテ','CONTENT_BASED','ALT_CATEGORY','YOUGA','PERSONALIZED',now()),
('ALT000086','オルトカテ_YOUGA_SF','オルトカテ','CONTENT_BASED','ALT_CATEGORY','YOUGA','PERSONALIZED',now()),
('ALT000087','オルトカテ_YOUGA_war','オルトカテ','CONTENT_BASED','ALT_CATEGORY','YOUGA','PERSONALIZED',now()),
('ALT000088','オルトカテ_FDRAMA','オルトカテ','CONTENT_BASED','ALT_CATEGORY','FDRAMA','PERSONALIZED',now()),
('ALT000089','オルトカテ_MUSIC_IDOL','オルトカテ','CONTENT_BASED','ALT_CATEGORY','MUSIC_IDOL','PERSONALIZED',now()),
('ALT000090','オルトカテ_VARIETY','オルトカテ','CONTENT_BASED','ALT_CATEGORY','VARIETY','PERSONALIZED',now()),
('ALT000091','オルトカテ_ANIME','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ANIME','PERSONALIZED',now()),
('ALT000092','オルトカテ_YOUGA','オルトカテ','CONTENT_BASED','ALT_CATEGORY','YOUGA','PERSONALIZED',now()),
('ALT000093','オルトカテ_DRAMA','オルトカテ','CONTENT_BASED','ALT_CATEGORY','DRAMA','PERSONALIZED',now()),
('ALT000094','オルトカテ_ADRAMA','オルトカテ','CONTENT_BASED','ALT_CATEGORY','ADRAMA','PERSONALIZED',now()),
('ALT000095','オルトカテ_DOCUMENT','オルトカテ','CONTENT_BASED','ALT_CATEGORY','DOCUMENT','PERSONALIZED',now()),
('ALT000096','オルトカテ_HOUGA','オルトカテ','CONTENT_BASED','ALT_CATEGORY','HOUGA','PERSONALIZED',now()),
('ALT000097','オルトカテ_KIDS','オルトカテ','CONTENT_BASED','ALT_CATEGORY','KIDS','PERSONALIZED',now())
